# Copyright (c) 2025-2026 BlackRoad OS, Inc. All Rights Reserved.
# Hadolint configuration
ignored:
  - DL3018  # Pin versions in apk add (not relevant - we use npm)
  - DL3059  # Multiple consecutive RUN instructions (intentional for caching)
