name: Feature Request
description: Propose a new feature or improvement for BlackRoad OS
title: "[Feature]: "
labels: ["type:feature", "status:backlog"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the feature you'd like to see. Include as much context as possible.

  - type: dropdown
    id: team
    attributes:
      label: Team
      description: Which area does this belong to?
      options:
        - Core Platform
        - Web / Frontend
        - Agents
        - Infrastructure / DevOps
        - Prism Console
        - CLI Tools
        - Documentation
        - Packs
        - AI / ML
        - Security
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this?
      options:
        - P2 - Normal
        - P1 - High
        - P0 - Critical
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve? Why do we need it?
      placeholder: "Currently there's no way to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work? Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you've thought about.

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: How big is this change?
      options:
        - Small (single file/script)
        - Medium (multiple files, one service)
        - Large (cross-service, new subsystem)
        - Epic (multi-sprint, architectural)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mockups, related repos, agent requirements, etc.
