# Copyright (c) 2025-2026 BlackRoad OS, Inc. All Rights Reserved.
name: Terraform CI

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
      terraform-version:
        type: string
        default: "1.7"

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}
      - run: terraform fmt -check -recursive
      - run: terraform init -backend=false
      - run: terraform validate
